
# docker-compose.yml
services:
  electrolux-to-mqtt:
    image: kirbownz/electrolux-to-mqtt:latest
    mem_limit: 128mb
    memswap_limit: 256mb
    restart: unless-stopped
    volumes:
      - ./config.yml:/app/config.yml
    environment:
      - LOG_LEVEL=info