# acme.sh --issue --stateless -k 2048 -f -d e2m.devaus.eu

server {
  server_name               e2m.devaus.eu;

  include                   /home/kirbo/nginx/includes/all.conf;
  include                   /home/kirbo/nginx/includes/listen_80.conf;
  root                      /home/kirbo/Projects/electrolux-to-mqtt/telemetry-backend/badge/;

  error_log                 /home/kirbo/logs/e2m.error.log;
  access_log                /home/kirbo/logs/e2m.access.log;

  location = / {
    return                  302 /users.svg;
  }

  location /telemetry {
    proxy_pass              http://localhost:3001;
    include                 /home/kirbo/nginx/includes/api_proxy.conf;
  }
}
